### ISSUE TITLE
Option to disable events/gestures

### ISSUE THREAD

**Issue by staghouse** [arunahuja94/react-native-flip-card-plus#1]
I have an interesting use case. I have a pan animator on a card that pans up and down, however, when using this component, which is otherwise perfect for me, my pan animator gets disabled in favor of the swiping that naturally occurs on the flip card component.

Is there a way to disable all user input events so that only a button can flip the card instead of a gesture?

**Comment by arunahuja94** [comment]
Hi @staghouse 

Please add the prop given below and check, if it works for you

> swipeable={false}

Thanks

**Comment by arunahuja94** [comment]
Hi @staghouse 

Please confirm if that worked for you, so that I can close this issue or if not then please let me know

Thanks

**Comment by staghouse** [comment]
Works - thanks!
